# Generated by Django 4.2.7 on 2025-09-19 09:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('college_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='College ID must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('password', models.CharField(max_length=128)),
                ('admission_type', models.CharField(choices=[('counseling', 'Counseling'), ('management', 'Management')], default='counseling', max_length=20)),
                ('college_fee', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('bus_fee', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
